### ISSUE TITLE
Crowdfunding

### ISSUE THREAD

**Issue by adelyte-chris** [adelyte/crestron-yahoo_weather#2]
We have received several inquiries during the past two months about fixing the module (or creating a new one).

There are several approaches we could take:
1. Add authentication to the existing module.
2. Find an open weather data feed that is likely to remain open.
3. Syndicate paid weather data and deploy our own weather data feed at `weather.adelyte.com`.

(Running our own weather data feed would have the added advantage that we could use IP address geolocation to provide weather data with zero configuration.)

Users interested in supporting a crowdfunding campaign should post the following information (see example):
1. Name
2. Company Name
3. Minimum Contribution Amount

If we receive enough interest, we'll launch a campaign on [Kickstarter](https://www.kickstarter.com).

**Comment by adelyte-chris** [comment]
Chris Massey
Adelyte Company
$100

**Comment by adelyte-austin** [comment]
Option 2 is working for now, using the new query.yahooapis and YQL services. Thanks again to user ptizzy for finding the solution.
