### ISSUE TITLE
Local Conditions/ Metadata getting chopped off 

### ISSUE THREAD

**Issue by jgirardi1td** [adelyte/crestron-yahoo_weather#5]
Local conditions/ Dynamic conditions getting chopped off - it will say "Mostly S" instead of "Mostly Sunny" etc as it should. Happens in Demo running on 3 series latest FW or AES 2 series on 4.003 FW from 2010

![image](https://cloud.githubusercontent.com/assets/26909903/24677828/27522752-1956-11e7-82c8-c9561003d48c.png)

![image](https://cloud.githubusercontent.com/assets/26909903/24677854/36a4cd90-1956-11e7-9140-99af7d3780ed.png)

**Comment by adelyte-austin** [comment]
Thanks for reporting the issue @jgirardi1td. I've confirmed this also happens on my processor, and have set a deadline of 2017-07-14 to deliver a fix.
